name: CI FastAPI Submit Task

on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/**'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn pytest jinja2

      - name: Launch FastAPI server
        run: |
          nohup uvicorn src.server:app --host 0.0.0.0 --port 8000 &
          sleep 10  # Laisse le temps au serveur de démarrer

      - name: Run tests
        run: pytest tests/
